steps:
# 0. 回避策：dockerfile (小文字) を DOCKERFILE (大文字) にコピー (修正！)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args: ['-c', 'cp dockerfile DOCKERFILE'] 

# 1. コンテナイメージをビルドするステップ
# ビルドファイルは DOCKERFILE を指定する（ここは変更なし）
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA', 
    '.', 
    '-f', 'DOCKERFILE' 
  ]
# ... 続くステップはそのまま
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA' ]

# 3. Cloud Run にデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'nba2k26-jpl',  # <-- Cloud Run のサービス名
    '--image', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA',
    '--region', 'asia-northeast1', # <-- デプロイ先のリージョン
    '--allow-unauthenticated',     # <-- 認証なしアクセスを許可
    '--platform', 'managed'        # <-- Cloud Run (managed) を指定
  ]

# 4. オプション：ロギング設定（エラーの解決）
options:
  logging: CLOUD_LOGGING_ONLY