steps:
# 1. コンテナイメージをビルドする (修正！)
# Cloud Buildはデフォルトでルートの Dockerfile を参照するため、これが正しい
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA', '.' ]

# 2. イメージをコンテナレジストリにプッシュする
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA' ]

# 3. Cloud Run にデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'nba2k26-jpl',
    '--image', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA',
    '--region', 'asia-northeast1', # あなたのリージョンに変更
    '--allow-unauthenticated',
    '--platform', 'managed'
  ]
options:
  logging: CLOUD_LOGGING_ONLY # ログエラー回避のため必要