steps:
# 0. 回避策：Dockerfileを大文字にコピーして強制的に認識させる (NEW!)
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args: ['-c', 'cp Dockerfile DOCKERFILE'] 

# 1. コンテナイメージをビルドするステップ (修正)
# ビルドファイルを DOCKERFILE に指定します
- name: 'gcr.io/cloud-builders/docker'
  args: [ 
    'build', 
    '-t', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA', 
    '.', 
    '-f', 'DOCKERFILE' # <--- ここを DOCKERFILE に変更
  ]

# ... 2, 3, 4 ステップはそのまま
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA' ]

# 3. Cloud Run にデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'nba2k26-jpl',  # <-- Cloud Run のサービス名
    '--image', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA',
    '--region', 'asia-northeast1', # <-- デプロイ先のリージョン
    '--allow-unauthenticated',     # <-- 認証なしアクセスを許可
    '--platform', 'managed'        # <-- Cloud Run (managed) を指定
  ]

# 4. オプション：ロギング設定（エラーの解決）
options:
  logging: CLOUD_LOGGING_ONLY