steps:
# 1. コンテナイメージをビルドする
# --fileオプションなし。すべて小文字の 'dockerfile' がルートにあると想定
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA', '.', '-f', 'dockerfile' ]

# 2. イメージをコンテナレジストリにプッシュする
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcrio/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA' ]

# 3. Cloud Run にデプロイする
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'nba2k26-jpl',
    '--image', 'gcr.io/winged-weft-474616-b5/nba2k-app:$COMMIT_SHA',
    '--region', 'asia-northeast1',
    '--allow-unauthenticated',
    '--platform', 'managed'
  ]
options:
  logging: CLOUD_LOGGING_ONLY